"""dropped grade column

Revision ID: ff28d49c8b07
Revises: 5ee30765baf2
Create Date: 2024-10-05 23:02:28.251174

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'ff28d49c8b07'
down_revision = '5ee30765baf2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('student', schema=None) as batch_op:
        batch_op.drop_column('grade')

    # ### end Alembic commands ###

def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('student', schema=None) as batch_op:
        batch_op.add_column(sa.Column('grade', mysql.VARCHAR(length=20), nullable=False))

    # ### end Alembic commands ###
