version: "3.8"

services:
  mysql:
    image: mysql:8.0
    container_name: mysql_container
    environment:
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./mysql-init:/docker-entrypoint-initdb.d/
    networks:
      - app_network

  api:
    build:
      context: .
      dockerfile: Dockerfile
    image: flask-api:${API_VERSION}
    container_name: flask_api
    environment:
      FLASK_APP: app.py
      DB_URL: ${DB_URL}  # Use the new DB_URL environment variable
      MIGRATIONS: "true"
    ports:
      - "5000:5000"
    depends_on:
      - mysql
    networks:
      - app_network

volumes:
  mysql_data:
    name: mysql_data

networks:
  app_network:
    name: app_network