version: "3.8"

services:
  mysql:
    image: mysql:8.0
    container_name: mysql_container
    environment:
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./mysql-init:/docker-entrypoint-initdb.d/  # Init script for both databases
    networks:
      - app_network

  api:
    build:
      context: .  # Use the current directory to build the API
      dockerfile: Dockerfile
    image: flask-api:${API_VERSION}
    container_name: flask_api
    environment:
      FLASK_APP: app.py
      DATABASE_URL_CONTAINER: ${DATABASE_URL_CONTAINER}  # DB URL inside the container
      MIGRATIONS: "true"  # Run migrations when the container starts
    ports:
      - "5000:5000"
    depends_on:
      - mysql
    networks:
      - app_network

volumes:
  mysql_data:
    name: mysql_data  # Persistent MySQL data

networks:
  app_network:
    name: app_network