apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: db-credentials
  namespace: student-api  # Namespace where you want the Kubernetes secrets to be created
spec:
  secretStoreRef:
    name: vault-backend  # Name of the ClusterSecretStore
    kind: SecretStore  
  target:
    name: mysql-secret
    creationPolicy: Owner
  data:
    - secretKey: MYSQL_ROOT_PASSWORD
      remoteRef:
        key: secret/mysql-root-password
        property: password
    - secretKey: MYSQL_DATABASE
      remoteRef:
        key: secret/mysql-database
        property: name
    - secretKey: DB_URL
      remoteRef:
        key: secret/mysql-url
        property: url
  refreshInterval: "1h"
