apiVersion: apps/v1
kind: Deployment
metadata:
  name: flask-app
  namespace: student-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: flask-app
  template:
    metadata:
      labels:
        app: flask-app
    spec:
      imagePullSecrets:
        - name: mysql-secret  # This secret holds DockerHub credentials for image pull
      containers:
        - name: flask-app
          image: srivatsarv21/one2n-bootcamp:6.1.0
          ports:
            - containerPort: 5000
          env:
            - name: DB_URL
              valueFrom:
                secretKeyRef:
                  name: mysql-secret
                  key: DB_URL
          resources:
            requests:
              memory: "512Mi"
              cpu: "500m"
            limits:
              memory: "1Gi"
              cpu: "1"
      initContainers:
        - name: db-upgrade
          image: srivatsarv21/one2n-bootcamp:6.1.0
          command: ["/bin/sh", "-c"]
          args:
            - |
              echo "Starting DB Migration"
              python3 -m flask db upgrade
              echo "DB Migration completed"
          env:
            - name: DB_URL
              valueFrom:
                secretKeyRef:
                  name: mysql-secret
                  key: DB_URL
          resources:
            requests:
              memory: "128Mi"
              cpu: "250m"
            limits:
              memory: "256Mi"
              cpu: "500m"
---
apiVersion: v1
kind: Service
metadata:
  name: flask-app-service
  namespace: student-api
spec:
  type: ClusterIP  # Change to NodePort for Minikube
  selector:
    app: flask-app
  ports:
    - protocol: TCP
      port: 5000  # Port exposed to the outside
      targetPort: 5000  # Port your Flask app listens to