apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: {{ .Values.externalSecret.name }}
  namespace: {{ .Values.namespace }}
spec:
  secretStoreRef:
    name: vault-backend
    kind: SecretStore
  target:
    name: {{ .Values.externalSecret.targetName }}
    creationPolicy: Owner
  data:
    - secretKey: MYSQL_ROOT_PASSWORD
      remoteRef:
        key: {{ .Values.externalSecret.mysqlRootPassword.key }}
        property: {{ .Values.externalSecret.mysqlRootPassword.property }}
    - secretKey: MYSQL_DATABASE
      remoteRef:
        key: {{ .Values.externalSecret.mysqlDatabase.key }}
        property: {{ .Values.externalSecret.mysqlDatabase.property }}
    - secretKey: DB_URL
      remoteRef:
        key: {{ .Values.externalSecret.mysqlUrl.key }}
        property: {{ .Values.externalSecret.mysqlUrl.property }}
    - secretKey: .dockerconfigjson
      remoteRef:
        key: {{ .Values.externalSecret.dockerhubConfig.key }}
        property: {{ .Values.externalSecret.dockerhubConfig.property }}
  refreshInterval: {{ .Values.externalSecret.refreshInterval }}
