name: CI Pipeline

on:
  push:
    branches:
      - milestone-4/setup-ci-pipeline
    paths:
      - 'milestone-4-setup-ci-pipeline/**'
      - '.github/**'
  pull_request:
    branches:
      - main
    paths:
      - 'milestone-4-setup-ci-pipeline/**'

jobs:
  ci-pipeline:
    runs-on: self-hosted

    env:
      MYSQL_ROOT_PASSWORD: ${{ secrets.MYSQL_ROOT_PASSWORD }}
      MYSQL_DATABASE: ${{ secrets.MYSQL_DATABASE }}
      DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
      DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}
      GITHUB_WORKSPACE: ${{ github.workspace }}
      DB_URL: ${{ secrets.DB_URL }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Create .env file
        run: |
          echo "DB_URL=mysql://root:${{ secrets.MYSQL_ROOT_PASSWORD }}@mysql_container:3306/${{ secrets.MYSQL_DATABASE }}" > $GITHUB_WORKSPACE/milestone-4-setup-ci-pipeline/.env
          echo "MYSQL_ROOT_PASSWORD=${{ secrets.MYSQL_ROOT_PASSWORD }}" >> $GITHUB_WORKSPACE/milestone-4-setup-ci-pipeline/.env
          echo "MYSQL_DATABASE=${{ secrets.MYSQL_DATABASE }}" >> $GITHUB_WORKSPACE/milestone-4-setup-ci-pipeline/.env
        env:
          GITHUB_WORKSPACE: ${{ github.workspace }}

      - name: Set up Python and Install dependencies
        run: |
          python3 -m venv $GITHUB_WORKSPACE/milestone-4-setup-ci-pipeline/venv
          source $GITHUB_WORKSPACE/milestone-4-setup-ci-pipeline/venv/bin/activate
          pip install --upgrade pip
          pip install -r $GITHUB_WORKSPACE/milestone-4-setup-ci-pipeline/requirements.txt
        env:
          GITHUB_WORKSPACE: ${{ github.workspace }}

      - name: Start MySQL and run services using Docker Compose
        run: |
          source $GITHUB_WORKSPACE/milestone-4-setup-ci-pipeline/venv/bin/activate
          docker compose up -d mysql && docker exec -it mysql_container bash -c "until mysqladmin ping -h localhost --silent; do sleep 1; done"
        working-directory: ./milestone-4-setup-ci-pipeline

      - name: Run linting
        run: |
          source $GITHUB_WORKSPACE/milestone-4-setup-ci-pipeline/venv/bin/activate
          make lint
        working-directory: ./milestone-4-setup-ci-pipeline

      - name: Run tests
        run: |
          source $GITHUB_WORKSPACE/milestone-4-setup-ci-pipeline/venv/bin/activate
          export PYTHONPATH=$GITHUB_WORKSPACE/milestone-4-setup-ci-pipeline
          pytest tests/test_app.py
        working-directory: ./milestone-4-setup-ci-pipeline

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push Docker image
        run: |
          source $GITHUB_WORKSPACE/milestone-4-setup-ci-pipeline/venv/bin/activate
          make build_flask_image
          make docker_push
        working-directory: ./milestone-4-setup-ci-pipeline