name: CI Pipeline

on:
  push:
    branches:
      - milestone-4/setup-ci-pipeline
    paths:
      - 'milestone-4-setup-ci-pipeline/**'
  pull_request:
    branches:
      - main
    paths:
      - 'milestone-4-setup-ci-pipeline/**'


jobs:
  ci-pipeline:
    runs-on: self-hosted

    env:
      MYSQL_ROOT_PASSWORD: ${{ secrets.MYSQL_ROOT_PASSWORD }}
      MYSQL_DATABASE: ${{ secrets.MYSQL_DATABASE }}
      DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
      DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}
      DB_HOST: mysql
      CI: true

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: |
          whoami
          hostname
          python -m pip install --upgrade pip
          pip install -r requirements.txt
        working-directory: ./milestone-4-setup-ci-pipeline

      - name: Start MySQL and run services using Docker Compose (run_db)
        run: |
          make run_db
        working-directory: ./milestone-4-setup-ci-pipeline

      - name: Run linting
        run: make lint
        working-directory: ./milestone-4-setup-ci-pipeline

      - name: Run tests
        run: make run_tests
        working-directory: ./milestone-4-setup-ci-pipeline

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push Docker image
        env:
          DOCKER_REPO: ${{ secrets.DOCKERHUB_USERNAME }}/one2n-bootcamp
        run: |
          make build_flask_image
          make docker_push
        working-directory: ./milestone-4-setup-ci-pipeline

      - name: Run docker 
        run: docker logs mysql_container
