name: CI Pipeline

# Trigger on push and pull request events
on:
  push:
    branches:
      - main
      - milestone-4/setup-ci-pipeline
  pull_request:
    branches:
      - main
      - milestone-4/setup-ci-pipeline
  workflow_dispatch:  # Allows manual trigger

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository
      - name: Checkout Code
        uses: actions/checkout@v2

      # Step 2: Set up Python environment
      - name: Set up Python 3.9
        uses: actions/setup-python@v2
        with:
          python-version: 3.9

      # Step 3: Install Python dependencies
      - name: Install Dependencies
        run: |
          pip install -r requirements.txt
          pip install flake8 pytest

      # Step 4: Run code linting with flake8
      - name: Run Code Linting
        run: |
          make lint

      # Step 5: Run tests using pytest
      - name: Run Tests
        run: |
          make run_tests

  docker-build-and-push:
    runs-on: ubuntu-latest
    needs: build-and-test  # Only runs if build-and-test job succeeds

    steps:
      # Step 1: Checkout the repository
      - name: Checkout Code
        uses: actions/checkout@v2

      # Step 2: Log in to DockerHub
      - name: Log in to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      # Step 3: Build Docker image
      - name: Build Docker Image
        run: |
          make build_flask_image

      # Step 4: Push Docker image to DockerHub
      - name: Push Docker Image
        run: |
          make docker_push